cmd/atlas: bump Go version to 1.19 due to url.JoinPath (#1296)
Running under `1.18` causes the following error:

```
internal/cmdapi/vercheck/vercheck.go:72:23: undefined: url.JoinPath
```